---
web:
  url: "https://mail.sina.com.cn/"

#sina邮箱
---
sina:
  loginNull: "请输入邮箱名"
  email: "您输入的邮箱名格式不正确"
  error: "登录名或密码错误"

---
#登录的账户密码
login:
  username: "wuya1303@sina.com"
  passwd: "admin123"






